# Generated by Django 4.1.7 on 2023-05-15 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='отчество')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('avatar',
                 models.ImageField(blank=True, null=True, upload_to='uploads/avatars/', verbose_name='аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профайл',
                'verbose_name_plural': 'профайлы',
            },
        ),
    ]
