# Generated by Django 4.1.7 on 2023-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_app', '0002_remove_profile_patronymic_remove_profile_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='телефон'),
        ),
    ]
