# Generated by Django 4.1.7 on 2023-04-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0003_alter_goods_full_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="наименование")),
            ],
            options={
                "verbose_name": "фирма",
                "verbose_name_plural": "фирмы",
            },
        ),
        migrations.AddField(
            model_name="goods",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop_app.company",
                verbose_name="компания производитель",
            ),
        ),
    ]
