# Generated by Django 4.1.7 on 2023-05-15 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0004_company_goods_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="goods",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="order",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="user",
        ),
        migrations.DeleteModel(
            name="Delivery",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
    ]
