# Generated by Django 4.1.7 on 2023-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders_app', '0003_alter_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='дата заказа'),
        ),
    ]
