# Generated by Django 4.1.7 on 2023-06-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders_app', '0005_alter_order_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='дата заказа'),
        ),
    ]
